import { Tag } from '@/components/HashTag';

export const HASHTAGS: Tag[] = [
  { id: 1, label: '#먹방', removable: false },
  { id: 2, label: '#Vlog', removable: false },
  { id: 3, label: '#Beauty', removable: false },
  { id: 4, label: '#Dogs', removable: false },
  { id: 5, label: '#BackEnd', removable: false },
  { id: 6, label: '#FrontEnd', removable: false },
  { id: 7, label: '#Game', removable: false },
  { id: 8, label: '#Music', removable: false },
  { id: 9, label: '#여행', removable: false },
  { id: 10, label: '#소설', removable: false },
  { id: 11, label: '#Health', removable: false },
  { id: 12, label: '#주식', removable: false },
  { id: 13, label: '#OOTD', removable: false },
  { id: 14, label: '#데일리룩', removable: false },
  { id: 15, label: '#photography', removable: false },
  { id: 16, label: '#핸드메이드', removable: false },
  { id: 17, label: '#Design', removable: false },
  { id: 18, label: '#인테리어', removable: false },
  { id: 19, label: '#맛집', removable: false },
  { id: 20, label: '#smallbusiness', removable: false },
  { id: 21, label: '#동기부여', removable: false },
  { id: 22, label: '#자기계발', removable: false },
  { id: 23, label: '#발레', removable: false },
  { id: 24, label: '#Fashion', removable: false },
  { id: 25, label: '#드라마', removable: false },
];
